// <auto-generated />
namespace Galeria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migr0615_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migr0615_));
        
        string IMigrationMetadata.Id
        {
            get { return "201706151644282_Migr0615_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
